require 'set'
require 'forwardable'

# On with the library...
require_relative 'turbine/properties'
require_relative 'turbine/collection'
require_relative 'turbine/edge'
require_relative 'turbine/errors'
require_relative 'turbine/graph'
require_relative 'turbine/pipeline/dsl'
require_relative 'turbine/pipeline/segment'
require_relative 'turbine/pipeline/filter'
require_relative 'turbine/pipeline/pump'
require_relative 'turbine/pipeline/transform'
require_relative 'turbine/pipeline/sender'
require_relative 'turbine/traversal/base'
require_relative 'turbine/traversal/breadth_first'
require_relative 'turbine/traversal/depth_first'
require_relative 'turbine/version'
require_relative 'turbine/node'
